package cn.jas.entity;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.headimg
     *
     * @mbg.generated
     */
    private String headimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.lv
     *
     * @mbg.generated
     */
    private Short lv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.exp
     *
     * @mbg.generated
     */
    private Integer exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.coins
     *
     * @mbg.generated
     */
    private Integer coins;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gems
     *
     * @mbg.generated
     */
    private Integer gems;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userid
     *
     * @return the value of users.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userid
     *
     * @param userid the value for users.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account
     *
     * @return the value of users.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account
     *
     * @param account the value for users.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.headimg
     *
     * @return the value of users.headimg
     *
     * @mbg.generated
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.headimg
     *
     * @param headimg the value for users.headimg
     *
     * @mbg.generated
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.lv
     *
     * @return the value of users.lv
     *
     * @mbg.generated
     */
    public Short getLv() {
        return lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.lv
     *
     * @param lv the value for users.lv
     *
     * @mbg.generated
     */
    public void setLv(Short lv) {
        this.lv = lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.exp
     *
     * @return the value of users.exp
     *
     * @mbg.generated
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.exp
     *
     * @param exp the value for users.exp
     *
     * @mbg.generated
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.coins
     *
     * @return the value of users.coins
     *
     * @mbg.generated
     */
    public Integer getCoins() {
        return coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.coins
     *
     * @param coins the value for users.coins
     *
     * @mbg.generated
     */
    public void setCoins(Integer coins) {
        this.coins = coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gems
     *
     * @return the value of users.gems
     *
     * @mbg.generated
     */
    public Integer getGems() {
        return gems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gems
     *
     * @param gems the value for users.gems
     *
     * @mbg.generated
     */
    public void setGems(Integer gems) {
        this.gems = gems;
    }
}